# **Tarea 3 - MER, Modelo relacional y SQL + Indexación.**
En la presente tarea Ud deberá:


1.   A partir de una especificación de requerimientos, crear un MER, su posterior Modelo relacional y responder consultas usando SQL.
2.   Mostrar que la indexación permite mejorar el rendimiento en el procesamiento de consultas.


*   La tarea se puede realizar en pareja.
*   Para responder a las consultas utilice las celdas ya definidas para ello.
*   El notebook debe estar bien presentado.
*   Todas las celdas de código deben estar ejecutadas.
*   La entrega de la tarea incluye una interrogación.<b>  En caso de no asistir a la interrogación la tarea será calificada con nota 1</b>.
*   Los archivos que deben entregar son los siguientes: (a) El presente notebook, (b) un script SQL, llamado createDB.sql, para la creación de las tablas y (c) un script, llamado insert.sql, que contenga la inserción de registros.
*   Para entregar incluya (a),(b) y (c) en un archivo comprimido.


**Fecha de entrega:** 25 de Junio hasta las 23h59, vía Aula Virtual.

# **PARTE 1. MER, Modelo Relacional y SQL.**

Una empresa desea diseñar una base de datos para almacenar en ella toda la información generada en cada uno de los proyectos que realiza. Para cada uno de los proyectos realizados interesa almacenar el código, descripción, valor del proyecto, meses de duración, fecha de inicio y fecha de fin. Los proyectos son realizados a clientes de los que se desea guardar nombre de la empresa, la persona de contacto, correo de contacto, teléfono, domicilio, giro y RUT. Un cliente puede tener varios proyectos, pero un proyecto es realizado para un único cliente y es gestionado por un jefe de proyectos. En los proyectos participan ingenieros de los que se dispone la siguiente información: Rut, nombre, domicilio, teléfono, sueldo, banco y número de cuenta. Un ingeniero puede participar en varios proyectos y en cada proyecto tiene asignado una cantidad fija de horas de trabajo a la semana. En los proyectos trabajan uno o más ingenieros. A fin de mes cada ingeniero recibe una planilla de sueldo que contiene el sueldo bruto, el sueldo líquido y para cada proyecto donde trabajó el último mes: el nombre del proyecto, la empresa y la cantidad de horas trabajadas.
Plantee un MER, que permita responder al menos los siguientes requerimientos: <br>

1. Cuáles son los proyectos activos en los cuales trabaja un determinado ingeniero?
2. Cuáles son los proyectos terminados donde trabajó la mayor cantidad de ingenieros?
3. Cuáles son los proyectos terminados en los cuales ha trabajado un determinado ingeniero en los últimos 12 meses?.
4. Cuál es el proyecto que la empresa más ha tardado en terminar?
5. Generar la planilla de sueldo para un determinado ingeniero.

## **(I) Inserte aquí el MER.**

Incluya en la siguiente lista todos los supuestos y comentarios que ayudarán a comprender sus decisiones de diseño:


*   
*

## **(II) Inserte aquí el Modelo relacional (opción Relational schema en ERDPlus)**

## **(III) Inserte aquí el script para la creación de tablas.**

```
CREATE TABLE Clientes
(
  Nombre VARCHAR(50) NOT NULL,
  Persona_de_contacto VARCHAR(50) NOT NULL,
  Correo_de_contacto VARCHAR(50) NOT NULL,
  Telefono INT NOT NULL,
  Domicilio VARCHAR(50) NOT NULL,
  Giro VARCHAR(50) NOT NULL,
  Rut_empresa INT NOT NULL,
  PRIMARY KEY (Rut_empresa)
);

CREATE TABLE Ingeniero
(
  Rut_ingeniero INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Domicilio VARCHAR(50) NOT NULL,
  Telefono INT NOT NULL,
  Sueldo FLOAT NOT NULL,
  Banco VARCHAR(50) NOT NULL,
  Numero_de_cuenta INT NOT NULL,
  PRIMARY KEY (Rut_ingeniero)
);

CREATE TABLE Proyecto
(
  Codigo INT NOT NULL,
  Descripcion VARCHAR(50) NOT NULL,
  Valor_Proyecto FLOAT NOT NULL,
  Duracion INT NOT NULL,
  Inicio DATE NOT NULL,
  Fin DATE NOT NULL,
  Rut_empresa INT NOT NULL,
  PRIMARY KEY (Codigo),
  FOREIGN KEY (Rut_empresa) REFERENCES Clientes(Rut_empresa)
);

CREATE TABLE Planilla
(
  Horas_Semanales INT NOT NULL,
  Codigo INT NOT NULL,
  Rut_ingeniero INT NOT NULL,
  FOREIGN KEY (Codigo) REFERENCES Proyecto(Codigo),
  FOREIGN KEY (Rut_ingeniero) REFERENCES Ingeniero(Rut_ingeniero)
);


```

## **(IV) Inserte aquí el script para la inserción de registros.**

```

INSERT INTO Clientes (Nombre, Persona_de_contacto, Correo_de_contacto, Telefono, Domicilio, Giro, Rut_empresa)
VALUES
('Empresa A', 'Juan Perez', 'juan.perez@empresaA.com', 123456789, 'Av. Principal 123', 'Tecnología', 1001),
('Empresa B', 'María Gomez', 'maria.gomez@empresaB.com', 987654321, 'Calle Secundaria 456', 'Construcción', 1002),
('Empresa C', 'Luis Martinez', 'luis.martinez@empresaC.com', 555555555, 'Pasaje Tercero 789', 'Consultoría', 1003);


INSERT INTO Ingeniero (Rut_ingeniero, Nombre, Domicilio, Telefono, Sueldo, Banco, Numero_de_cuenta)
VALUES
(2001, 'Carlos Sánchez', 'Av. Tecnológica 123', 123456789, 2500.50, 'Banco Estado', 1234567890),
(2002, 'Ana López', 'Calle Innovación 456', 987654321, 2700.75, 'Banco Chile', 9876543210),
(2003, 'Pedro Fernandez', 'Pasaje Innovador 789', 555555555, 3000.00, 'Banco Santander', 1122334455);

INSERT INTO Proyecto (Codigo, Descripcion, Valor_Proyecto, Duracion, Inicio, Fin, Rut_empresa)
VALUES
(1, 'Proyecto A', 15000.75, 12, '2023-01-01', '2023-12-31', 1001),
(2, 'Proyecto B', 20000.50, 6, '2023-03-01', '2023-08-31', 1002),
(3, 'Proyecto C', 10000.25, 9, '2023-02-01', '2023-10-31', 1003);

INSERT INTO Planilla (Horas_Semanales, Sueldo_Bruto, Sueldo_liquido, Codigo, Rut_ingeniero)
VALUES
(40, 2000.00, 1800.00, 1, 2001),
(30, 1500.00, 1350.00, 1, 2002),
(20, 1000.00, 900.00, 2, 2003),
(35, 1750.00, 1575.00, 2, 2001),
(25, 1250.00, 1125.00, 3, 2002),
(30, 1500.00, 1350.00, 3, 2003);

```

## **(V) Implementación de la BD y respuestas a los requerimientos.**

###**Preliminares (crear tablas, insertar registros,conectarse a la BD, consultar el catálogo de la BD, etc.)**

In [1]:
import pandas as pd
import sqlite3

In [2]:
pd.reset_option('display.max_columns')
pd.reset_option('display.max_rows')
pd.reset_option('display.max_colwidth')
pd.reset_option('display.width')

In [3]:
import sqlite3

conn = sqlite3.connect('Proyecto.db')
cursor = conn.cursor()

# Leer el archivo SQL
with open('createDB.sql', 'r') as sql_file:
    sql_script = sql_file.read()

# Ejecutar el script SQL
cursor.executescript(sql_script)
conn.commit()
conn.close()

In [5]:
import sqlite3

conn = sqlite3.connect('Proyecto.db')
cursor = conn.cursor()

# Leer el archivo SQL de inserción de datos
with open('insert.sql', 'r') as sql_file:
    sql_script = sql_file.read()

cursor.executescript(sql_script)
conn.commit()
conn.close()

In [7]:
!pip -q install faker

In [8]:
import pandas as pd
import sqlite3
from faker import Faker
import random
from datetime import datetime, timedelta

# Crear una instancia de Faker
fake = Faker()

# Conectar a la base de datos
conn = sqlite3.connect('Proyecto.db')
cursor = conn.cursor()

# Función para generar datos para la tabla Clientes
def generar_datos_clientes(n):
    clientes = []
    for _ in range(n):
        nombre = fake.company()
        persona_contacto = fake.name()
        correo_contacto = fake.email()
        telefono = fake.random_number(digits=8, fix_len=True)
        domicilio = fake.address().replace('\n', ', ')
        giro = fake.bs()
        rut_empresa = fake.random_number(digits=9, fix_len=True)
        clientes.append((nombre, persona_contacto, correo_contacto, telefono, domicilio, giro, rut_empresa))
    return clientes

# Función para generar datos para la tabla Ingeniero
def generar_datos_ingenieros(n):
    ingenieros = []
    for _ in range(n):
        rut_ingeniero = fake.random_number(digits=9, fix_len=True)
        nombre = fake.name()
        domicilio = fake.address().replace('\n', ', ')
        telefono = fake.random_number(digits=8, fix_len=True)
        sueldo = round(random.uniform(1000, 10000), 2)
        banco = fake.company()
        numero_cuenta = fake.random_number(digits=10, fix_len=True)
        ingenieros.append((rut_ingeniero, nombre, domicilio, telefono, sueldo, banco, numero_cuenta))
    return ingenieros

# Función para generar datos para la tabla Proyecto
def generar_datos_proyectos(n, rut_empresas):
    proyectos = []
    for _ in range(n):
        codigo = fake.random_number(digits=5, fix_len=True)
        descripcion = fake.catch_phrase()
        valor_proyecto = round(random.uniform(50000, 500000), 2)
        duracion = random.randint(1, 24)
        inicio = fake.date_between(start_date='-2y', end_date='today')
        fin = inicio + timedelta(days=duracion*30)
        rut_empresa = random.choice(rut_empresas)
        proyectos.append((codigo, descripcion, valor_proyecto, duracion, inicio, fin, rut_empresa))
    return proyectos

# Función para generar datos para la tabla Planilla
def generar_datos_planilla(n, codigos_proyectos, rut_ingenieros):
    planillas = []
    for _ in range(n):
        horas_semanales = random.randint(20, 40)
        codigo = random.choice(codigos_proyectos)
        rut_ingeniero = random.choice(rut_ingenieros)
        planillas.append((horas_semanales, codigo, rut_ingeniero))
    return planillas

# Generar datos
clientes = generar_datos_clientes(50)
ingenieros = generar_datos_ingenieros(50)
rut_empresas = [cliente[6] for cliente in clientes]
proyectos = generar_datos_proyectos(50, rut_empresas)
codigos_proyectos = [proyecto[0] for proyecto in proyectos]
rut_ingenieros = [ingeniero[0] for ingeniero in ingenieros]
planillas = generar_datos_planilla(100, codigos_proyectos, rut_ingenieros)

# Insertar datos en la base de datos
cursor.executemany('INSERT INTO Clientes VALUES (?, ?, ?, ?, ?, ?, ?)', clientes)
cursor.executemany('INSERT INTO Ingeniero VALUES (?, ?, ?, ?, ?, ?, ?)', ingenieros)
cursor.executemany('INSERT INTO Proyecto VALUES (?, ?, ?, ?, ?, ?, ?)', proyectos)
cursor.executemany('INSERT INTO Planilla VALUES (?, ?, ?)', planillas)

conn.commit()

C:\Users\UsuarioCompuElite\AppData\Local\Temp\ipykernel_58444\3012951264.py:78: DeprecationWarning: The default date adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  cursor.executemany('INSERT INTO Proyecto VALUES (?, ?, ?, ?, ?, ?, ?)', proyectos)

### **Consulta 1**

Cuáles son los proyectos activos en los cuales trabaja un determinado ingeniero?

In [9]:
query=''' SELECT *
          FROM Proyecto JOIN Planilla using(Codigo) JOIN Ingeniero USING (Rut_ingeniero)
          '''

pd.read_sql_query(query,conn)

,Codigo,Descripcion,Valor_Proyecto,Duracion,Inicio,Fin,Rut_empresa,Horas_Semanales,Rut_ingeniero,Nombre,Domicilio,Telefono,Sueldo,Banco,Numero_de_cuenta
0,1,Proyecto A,15000.75,12,2023-01-01,2023-12-31,1001,40,2001,Carlos SÃ¡nchez,Av. TecnolÃ³gica 123,123456789,2500.50,Banco Estado,1234567890
1,1,Proyecto A,15000.75,12,2023-01-01,2023-12-31,1001,30,2002,Ana LÃ³pez,Calle InnovaciÃ³n 456,987654321,2700.75,Banco Chile,9876543210
2,2,Proyecto B,20000.50,6,2023-03-01,2023-08-31,1002,20,2003,Pedro Fernandez,Pasaje Innovador 789,555555555,3000.00,Banco Santander,1122334455
3,2,Proyecto B,20000.50,6,2023-03-01,2023-08-31,1002,35,2001,Carlos SÃ¡nchez,Av. TecnolÃ³gica 123,123456789,2500.50,Banco Estado,1234567890
4,3,Proyecto C,10000.25,9,2023-02-01,2023-10-31,1003,25,2002,Ana LÃ³pez,Calle InnovaciÃ³n 456,987654321,2700.75,Banco Chile,9876543210
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,65633,Cloned multi-tasking secured line,72660.27,10,2023-09-28,2024-07-24,322647399,24,731480601,Alison Hill,"9401 Andrea Forges, Johnfort, GA 84823",81343503,6221.90,"Curry, Mayo and Hunt",8845920784
102,76902,Grass-roots multimedia knowledgebase,366265.01,15,2023-02-25,2024-05-20,322647399,34,697140827,Christopher Hamilton,"USS Norris, FPO AE 78447",41074710,7566.26,"Castro, Morales and Johnson",6446649268
103,79605,Future-proofed upward-trending synergy,408231.59,14,2024-04-30,2025-06-24,228737193,37,910806780,Kelly Oliver,"86271 William Square, Robinmouth, AR 69594",46411147,4433.93,Johnson-Bradley,6701378053
104,24619,De-engineered holistic knowledge user,274904.22,1,2023-06-12,2023-07-12,665765331,30,510629027,Michele Fernandez,"53179 Jeffrey Mountains Apt. 101, Goodmantown,...",74602232,3493.15,Harris Group,7129838656
105,60515,Universal well-modulated protocol,416472.24,3,2023-05-07,2023-08-05,495745772,25,810544433,Devin Cruz,"9553 Bennett Estate Suite 922, Port Whitney, A...",86198477,3759.97,"Jones, Lucas and Munoz",9566731692

### **Consulta 2**

Cuáles son los proyectos terminados donde trabajó la mayor cantidad de ingenieros?

In [10]:
query2='''SELECT p.Descripcion, p.Duracion, p.Inicio, p.Fin, count(distinct t.Rut_ingeniero) as Ingenieros
          FROM Proyecto as p JOIN Planilla as t using(Codigo) JOIN Ingeniero USING (Rut_ingeniero)
          WHERE Fin < date('now')
          GROUP BY Codigo
          ORDER BY Ingenieros DESC
          LIMIT 5'''

pd.read_sql_query(query2,conn)

,Descripcion,Duracion,Inicio,Fin,Ingenieros
0,Business-focused uniform conglomeration,4,2022-11-25,2023-03-25,6
1,Universal well-modulated protocol,3,2023-05-07,2023-08-05,4
2,Ameliorated foreground Graphic Interface,4,2024-02-12,2024-06-11,3
3,Proactive 24/7 moderator,13,2023-03-24,2024-04-17,3
4,Organized national interface,9,2022-07-25,2023-04-21,3

### **Consulta 3**

Cuáles son los proyectos terminados en los cuales ha trabajado un determinado ingeniero en los últimos 12 meses?.

In [11]:
query3='''SELECT *
          FROM Proyecto as p JOIN Planilla as t using(Codigo) JOIN Ingeniero USING (Rut_ingeniero)
          WHERE Fin < date('now') AND date('now') - Inicio <= 12 AND Rut_ingeniero = 518528546
          '''

pd.read_sql_query(query3,conn)

Empty DataFrame
Columns: [Codigo, Descripcion, Valor_Proyecto, Duracion, Inicio, Fin, Rut_empresa, Horas_Semanales, Rut_ingeniero, Nombre, Domicilio, Telefono, Sueldo, Banco, Numero_de_cuenta]
Index: []

###**Consulta 4**

Cuál es el proyecto que la empresa más ha tardado en terminar?

In [ ]:
query4='''SELECT *
          FROM Proyecto as p
          Order by DATE(p.Fin - p.Inicio) DESC
          LIMIT 5
          '''

pd.read_sql_query(query4,conn)

,Codigo,Descripcion,Valor_Proyecto,Duracion,Inicio,Fin,Rut_empresa
0,52824,De-engineered static contingency,366935.72,15,2022-11-29,2024-02-22,301764792
1,28433,Re-engineered asymmetric model,425128.56,22,2023-12-22,2025-10-12,188014550
2,49071,Synchronized executive access,290536.92,24,2023-05-16,2025-05-05,294158552
3,84133,Managed static leverage,373923.62,19,2022-10-08,2024-04-30,473354003
4,20476,Monitored interactive time-frame,317190.75,23,2024-04-15,2026-03-06,997029016

###**Consulta 5**

Generar la planilla de sueldo para un determinado ingeniero.

En los proyectos trabajan uno o más ingenieros. A fin de mes cada ingeniero recibe una planilla de sueldo que contiene el sueldo bruto, el sueldo líquido y para cada proyecto donde trabajó el último mes: el nombre del proyecto, la empresa y la cantidad de horas trabajadas. Plantee un MER, que permita responder al menos los siguientes requerimientos:

In [ ]:
query5='''SELECT Nombre,COUNT(*) AS 'Numero de proyectos', sueldo_bruto, COUNT(*)*Sueldo_Bruto as Planilla
          FROM Proyecto as p JOIN Planilla as t using(Codigo) JOIN Ingeniero USING (Rut_ingeniero)
          GROUP BY Rut_ingeniero


          '''

pd.read_sql_query(query5,conn)

            Nombre  Numero de proyectos  Sueldo_Bruto  Planilla
0   Carlos Sánchez                    2        2000.0    4000.0
1        Ana López                    2        1500.0    3000.0
2  Pedro Fernandez                    2        1000.0    2000.0

# **PARTE 2. Indexación.**

En esta parte Ud deberá evaluar el rendimiento de algunas consultas sobre la BD Flights (disponible para descarga desde el Aula). Esta BD es muy sencilla y consta de sólo una tabla.

Para evaluar el rendimiento deberá:

1. Ejecute la consulta de más abajo.
2. Calcule su tiempo de respuesta.
3. Decidir sobre cual atributo definir un índice para mejorar el tiempo de respuesta (fundamente su decisión).
4. Ejecutar nuevamente la consulta con el índice ya creado.
5. Mostrar que el tiempo de respuesta ha mejorado.

```
Consulta (a)
  SELECT DISTINCT carrier_id
  FROM Flights
  WHERE origin_city = 'Seattle WA' AND actual_time <= 180;
```

Repita el mismo procedimiento para la siguiente consulta:

```
Consulta (b)
  SELECT DISTINCT F2.origin_city
  FROM Flights F1, Flights F2
  WHERE F1.dest_city = F2.dest_city
    AND F1.origin_city='Gunnison CO'
    AND F1.actual_time <= 30;
```

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import sqlite3
import zipfile
import pandas as pd

ruta= '/content/drive/MyDrive/Universidad/flight.zip'
zip_ref = zipfile.ZipFile(ruta, 'r')
zip_ref.extractall('/content/drive/MyDrive/Universidad')
zip_ref.close()

In [ ]:
conn = sqlite3.connect('/content/drive/MyDrive/Universidad/flight.db')
cursor=conn.cursor()
pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table'",conn)

      name
0  FLIGHTS

In [ ]:
df = pd.read_sql_query("SELECT * FROM Flights", conn)

In [ ]:
#PRAGMA table_info(nombre_de_la_tabla)

pd.read_sql_query("PRAGMA table_info(Flights)",conn)

    cid             name         type  notnull dflt_value  pk
0     0              fid          INT        0       None   1
1     1             year          INT        0       None   0
2     2         month_id          INT        0       None   0
3     3     day_of_month          INT        0       None   0
4     4   day_of_week_id          INT        0       None   0
5     5       carrier_id   VARCHAR(3)        0       None   0
6     6       flight_num          INT        0       None   0
7     7      origin_city  VARCHAR(34)        0       None   0
8     8     origin_state  VARCHAR(47)        0       None   0
9     9        dest_city  VARCHAR(34)        0       None   0
10   10       dest_state  VARCHAR(46)        0       None   0
11   11  departure_delay       DOUBLE        0       None   0
12   12         taxi_out       DOUBLE        0       None   0
13   13    arrival_delay       DOUBLE        0       None   0
14   14         canceled          INT        0       None   0
15   15      actual_time       DOUBLE        0       None   0
16   16         distance       DOUBLE        0       None   0

In [ ]:
cursor.execute("PRAGMA index_list(Flights);")
cursor.fetchall()

[(0, 'sqlite_autoindex_FLIGHTS_1', 1, 'pk', 0)]

In [ ]:

cursor.execute("PRAGMA index_info(sqlite_autoindex_FLIGHTS_1);")
cursor.fetchall()

[(0, 0, 'fid')]

## **Consulta (a)**

In [ ]:
import time

In [ ]:

query='''
  SELECT DISTINCT carrier_id
  FROM Flights
  WHERE origin_city = 'Seattle WA' AND actual_time <= 180;
  '''

In [ ]:
import scipy.stats as stats
attribute = ['carrier_id','origin_city','actual_time']
print(df[attribute].describe(include='all'))

attribute = ['origin_city','actual_time','dest_city']

print('\n')
for i in attribute:
  freq = df[i].value_counts(normalize=True)
  entropy = stats.entropy(freq)

  print(f"Entropía para {i}: {entropy}")
  print('\n')

       carrier_id origin_city actual_time
count     1148675     1148675     1148675
unique         22         327         644
top            WN  Chicago IL
freq       202376       73317       22188


Entropía para origin_city: 4.36415892033133


Entropía para actual_time: 5.478936318453564


Entropía para dest_city: 4.366174381331299

Explain query plan antes de testear los indices

In [ ]:
cursor.execute('DROP INDEX IF EXISTS idx_1')
cursor.execute('DROP INDEX IF EXISTS idx_2')
cursor.execute('DROP INDEX IF EXISTS idx_3')

cursor.execute('ANALYZE')

pd.read_sql_query("EXPLAIN QUERY PLAN SELECT DISTINCT carrier_id FROM Flights WHERE origin_city = 'Seattle WA' AND actual_time <= 180; ",conn)

   id  parent  notused                        detail
0   3       0        0                  SCAN Flights
1  16       0        0  USE TEMP B-TREE FOR DISTINCT

*   Como vimos al principio la tabla solo tiene indexado el atributo fid ya que este es clave primaria, como se usa un distinct en carrier_id no seria mala indea indexar solo a este en un indice
*

In [ ]:

cursor.execute('DROP INDEX IF EXISTS idx_1')
cursor.execute('DROP INDEX IF EXISTS idx_2')
cursor.execute('DROP INDEX IF EXISTS idx_3')
cursor.execute('DROP INDEX IF EXISTS carrier_id')


create_index_sql = '''
CREATE INDEX idx_1 ON Flights(origin_city,actual_time);
'''
cursor.execute(create_index_sql)
create_index_sql = '''
CREATE INDEX carrier_id ON Flights(carrier_id);
'''
cursor.execute(create_index_sql)


cursor.execute('ANALYZE')

pd.read_sql_query("EXPLAIN QUERY PLAN SELECT DISTINCT carrier_id FROM Flights WHERE origin_city = 'Seattle WA' AND actual_time <= 180; ",conn)

   id  parent  notused                                                              detail
0   4       0        0  SEARCH Flights USING INDEX idx_1 (origin_city=? AND actual_time<?)
1  17       0        0                                        USE TEMP B-TREE FOR DISTINCT

Como podemos

In [ ]:

cursor.execute('DROP INDEX IF EXISTS idx_1')
cursor.execute('DROP INDEX IF EXISTS idx_2')

conn.commit()


start_time_0 = time.time()

pd.read_sql_query(query,conn)

end_time_0 = time.time()
print("Tiempo de respuesta:", end_time_0 - start_time_0)

create_index_sql = '''
CREATE INDEX idx_1 ON Flights(origin_city,actual_time,carrier_id);
'''


cursor.execute(create_index_sql)


conn.commit()

start_time_1 = time.time()

pd.read_sql_query(query,conn)

end_time_1 = time.time()
print("Tiempo de respuesta despues del index:", end_time_1 - start_time_1)

Tiempo de respuesta: 0.4720773696899414
Tiempo de respuesta despues del index: 0.0032079219818115234

Tiempo de respuesta: 0.47553110122680664
Tiempo de respuesta despues del index: 0.0032134056091308594

## **Consulta (b)**

Debido a que la mayoria de atributos son categoricos el describe puede que no nos de una parte de la informacion como la distribucion estandar pero podemos ingeniarnosla con la entropia del atributo



Índices y Entropía

    Alta Entropía:
        Descripción: Los valores del atributo están distribuidos de manera más uniforme y hay una mayor variedad de categorías.
        Ventajas: Los índices en atributos de alta entropía tienden a ser más selectivos, lo que puede mejorar el rendimiento de las consultas que buscan valores específicos. Esto se debe a que cada valor tiene una menor probabilidad de repetirse.
        Desventajas: Si el número de valores únicos es extremadamente alto, el tamaño del índice también puede ser grande, lo que puede aumentar el costo de mantenimiento del índice.

    Baja Entropía:
        Descripción: Unas pocas categorías dominan la distribución del atributo.
        Ventajas: Los índices en atributos de baja entropía pueden ser útiles para consultas que buscan las categorías más frecuentes. Estos índices suelen ser más pequeños y menos costosos de mantener.
        Desventajas: Los índices en atributos de baja entropía pueden ser menos selectivos, lo que puede reducir el rendimiento de las consultas que buscan valores específicos, ya que muchas filas pueden tener el mismo valor del atributo.

In [ ]:
query_2='''   SELECT DISTINCT F2.origin_city
  FROM Flights F1, Flights F2
  WHERE F1.dest_city = F2.dest_city
    AND F1.origin_city='Gunnison CO'
    AND F1.actual_time <= 30;
    '''

In [ ]:
import scipy.stats as stats
attribute = ['origin_city','actual_time','dest_city']
print(df[attribute].describe(include='all'))

attribute = ['origin_city','actual_time','dest_city']

print('\n')
for i in attribute:
  freq = df[i].value_counts(normalize=True)
  entropy = stats.entropy(freq)

  print(f"Entropía para {i}: {entropy}")
  print('\n')

       origin_city actual_time   dest_city
count      1148675     1148675     1148675
unique         327         644         326
top     Chicago IL              Chicago IL
freq         73317       22188       73279


Entropía para origin_city: 4.36415892033133


Entropía para actual_time: 5.478936318453564


Entropía para dest_city: 4.366174381331299

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

'''
pd.reset_option('display.max_columns')
pd.reset_option('display.max_rows')
pd.reset_option('display.max_colwidth')
pd.reset_option('display.width')

'''

Explicacion del plan de la query sin niguna indexacion

In [ ]:

cursor.execute('DROP INDEX IF EXISTS idx_1')
cursor.execute('DROP INDEX IF EXISTS idx_2')
cursor.execute('DROP INDEX IF EXISTS idx_3')

cursor.execute('ANALYZE')

pd.read_sql_query("EXPLAIN QUERY PLAN SELECT DISTINCT F2.origin_city FROM Flights F1, Flights F2 WHERE F1.dest_city = F2.dest_city AND F1.origin_city='Gunnison CO' AND F1.actual_time <= 30",conn)

   id  parent  notused                                                  detail
0   4       0        0                                                 SCAN F1
1  20       0        0  SEARCH F2 USING AUTOMATIC COVERING INDEX (dest_city=?)
2  32       0        0                            USE TEMP B-TREE FOR DISTINCT

In [ ]:

cursor.execute('DROP INDEX IF EXISTS idx_1')
cursor.execute('DROP INDEX IF EXISTS idx_2')
cursor.execute('DROP INDEX IF EXISTS idx_3')



create_index_sql = '''
CREATE INDEX idx_2 ON Flights(origin_city);
'''
cursor.execute(create_index_sql)

create_index_sql = '''
CREATE INDEX idx_3 ON Flights(dest_city,origin_city,actual_time);
'''
cursor.execute(create_index_sql)

cursor.execute('ANALYZE')

pd.read_sql_query("EXPLAIN QUERY PLAN SELECT DISTINCT F2.origin_city FROM Flights F1, Flights F2 WHERE F1.dest_city = F2.dest_city AND F1.origin_city='Gunnison CO' AND F1.actual_time <= 30",conn)

,id,parent,notused,detail
0,5,0,0,SCAN F2 USING INDEX idx_2
1,8,0,0,SEARCH F1 USING COVERING INDEX idx_3 (dest_city=? AND origin_city=? AND actual_time<?)

In [ ]:
cursor.execute('DROP INDEX IF EXISTS idx_1')
cursor.execute('DROP INDEX IF EXISTS idx_2')
cursor.execute('DROP INDEX IF EXISTS idx_3')
conn.commit()
#----------------------------------------------------------------------------------------#
#Tomamos el tiempo de la consulta sin indices

start_time_2 = time.time()
pd.read_sql_query(query_2,conn)

end_time_2 = time.time()
print("Tiempo de respuesta:", end_time_2 - start_time_2)

#----------------------------------------------------------------------------------------#
#Creamos los indices

create_index_sql = '''
CREATE INDEX idx_2 ON Flights(origin_city);
'''
cursor.execute(create_index_sql)

create_index_sql = '''
CREATE INDEX idx_3 ON Flights(dest_city,origin_city,actual_time);
'''
cursor.execute(create_index_sql)


conn.commit()

#----------------------------------------------------------------------------------------#
#Tomamos el tiempo de la consulta despues de aplicado los indices
start_time_3 = time.time()

pd.read_sql_query(query_2,conn)

end_time_3 = time.time()
print("Tiempo de respuesta:", end_time_3 - start_time_3)

Tiempo de respuesta: 1.1907081604003906
Tiempo de respuesta: 0.0033490657806396484



Tiempo de respuesta: 1.310753583908081
Tiempo de respuesta: 0.005269289016723633